## Import libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

## Import training data

In [2]:
df_train = pd.read_csv(r"C:\Users\dell\Downloads\train (6).csv")
df_train.head()

id     BertzCT       Chi1     Chi1n      Chi1v     Chi2n      Chi2v  \
0   0  323.390782   9.879918  5.875576   5.875576  4.304757   4.304757   
1   1  273.723798   7.259037  4.441467   5.834958  3.285046   4.485235   
2   2  521.643822  10.911303  8.527859  11.050864  6.665291   9.519706   
3   3  567.431166  12.453343  7.089119  12.833709  6.478023  10.978151   
4   4  112.770735   4.414719  2.866236   2.866236  1.875634   1.875634   

      Chi3v     Chi4n  EState_VSA1  ...  SlogP_VSA3  VSA_EState9  fr_COO  \
0  2.754513  1.749203     0.000000  ...    4.794537    35.527357       0   
1  2.201375  1.289775    45.135471  ...   13.825658    44.707310       0   
2  5.824822  1.770579    15.645394  ...   17.964475    45.660120       0   
3  7.914542  3.067181    95.639554  ...   31.961948    87.509997       0   
4  1.036450  0.727664    17.980451  ...    9.589074    33.333333       2   

   fr_COO2  EC1  EC2  EC3  EC4  EC5  EC6  
0        0    1    1    0    0    0    0  
1        0    0    1    1    0    0    0  
2        0    1    1    0    0    1    0  
3        0    1    1    0    0    0    0  
4        2    1    0    1    1    1    0  

[5 rows x 38 columns]

## Explore training data

In [3]:
df_train.shape

(14838, 38)

In [4]:
df_train.size

563844

In [5]:
df_train.describe()

id       BertzCT          Chi1         Chi1n         Chi1v  \
count  14838.000000  14838.000000  14838.000000  14838.000000  14838.000000   
mean    7418.500000    515.153604      9.135189      5.854307      6.738497   
std     4283.505982    542.456370      6.819989      4.647064      5.866444   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%     3709.250000    149.103601      4.680739      2.844556      2.932842   
50%     7418.500000    290.987941      6.485270      4.052701      4.392859   
75%    11127.750000    652.652585     11.170477      7.486791      8.527859   
max    14837.000000   4069.959780     69.551167     50.174588     53.431954   

              Chi2n         Chi2v         Chi3v         Chi4n   EState_VSA1  \
count  14838.000000  14838.000000  14838.000000  14838.000000  14838.000000   
mean       4.432570      5.253221      3.418749      1.773472     29.202823   
std        3.760516      4.925065      3.436208      1.865898     31.728679   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.949719      2.034468      1.160763      0.503897      5.969305   
50%        2.970427      3.242775      1.948613      1.073261     17.353601   
75%        5.788793      6.609350      4.502070      2.534281     44.876559   
max       32.195368     34.579313     22.880836     16.072810    363.705954   

       ...    SlogP_VSA3   VSA_EState9        fr_COO       fr_COO2  \
count  ...  14838.000000  14838.000000  14838.000000  14838.000000   
mean   ...     13.636941     49.309959      0.458215      0.459226   
std    ...     14.598554     29.174824      0.667948      0.668111   
min    ...      0.000000     -5.430556      0.000000      0.000000   
25%    ...      4.794537     30.000000      0.000000      0.000000   
50%    ...      9.589074     41.666667      0.000000      0.000000   
75%    ...     14.912664     56.090650      1.000000      1.000000   
max    ...    115.406157    384.450519      8.000000      8.000000   

                EC1           EC2           EC3           EC4           EC5  \
count  14838.000000  14838.000000  14838.000000  14838.000000  14838.000000   
mean       0.667745      0.798962      0.313789      0.279081      0.144831   
std        0.471038      0.400790      0.464047      0.448562      0.351942   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      1.000000      0.000000      0.000000      0.000000   
50%        1.000000      1.000000      0.000000      0.000000      0.000000   
75%        1.000000      1.000000      1.000000      1.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

                EC6  
count  14838.000000  
mean       0.151570  
std        0.358616  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 38 columns]

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14838 entries, 0 to 14837
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 14838 non-null  int64  
 1   BertzCT            14838 non-null  float64
 2   Chi1               14838 non-null  float64
 3   Chi1n              14838 non-null  float64
 4   Chi1v              14838 non-null  float64
 5   Chi2n              14838 non-null  float64
 6   Chi2v              14838 non-null  float64
 7   Chi3v              14838 non-null  float64
 8   Chi4n              14838 non-null  float64
 9   EState_VSA1        14838 non-null  float64
 10  EState_VSA2        14838 non-null  float64
 11  ExactMolWt         14838 non-null  float64
 12  FpDensityMorgan1   14838 non-null  float64
 13  FpDensityMorgan2   14838 non-null  float64
 14  FpDensityMorgan3   14838 non-null  float64
 15  HallKierAlpha      14838 non-null  float64
 16  HeavyAtomMolWt     148

In [7]:
#checking null values
df_train.isnull().sum()

id                   0
BertzCT              0
Chi1                 0
Chi1n                0
Chi1v                0
Chi2n                0
Chi2v                0
Chi3v                0
Chi4n                0
EState_VSA1          0
EState_VSA2          0
ExactMolWt           0
FpDensityMorgan1     0
FpDensityMorgan2     0
FpDensityMorgan3     0
HallKierAlpha        0
HeavyAtomMolWt       0
Kappa3               0
MaxAbsEStateIndex    0
MinEStateIndex       0
NumHeteroatoms       0
PEOE_VSA10           0
PEOE_VSA14           0
PEOE_VSA6            0
PEOE_VSA7            0
PEOE_VSA8            0
SMR_VSA10            0
SMR_VSA5             0
SlogP_VSA3           0
VSA_EState9          0
fr_COO               0
fr_COO2              0
EC1                  0
EC2                  0
EC3                  0
EC4                  0
EC5                  0
EC6                  0
dtype: int64

In [8]:
#checking duplicate values
df_train.duplicated().sum()

0

### Observation:

There are 38 columns and nearly 15,000 rows. There are no null values and no duplicate values. All columns are numerical in nature.

### Removing unnecessary columns

In [9]:
del df_train['id']

## Importing testing data

In [10]:
df_test = pd.read_csv(r"C:\Users\dell\Downloads\test (6).csv")
df_test.head()

id      BertzCT       Chi1      Chi1n      Chi1v      Chi2n      Chi2v  \
0  14838   344.632371   7.283603   4.473966   5.834958   3.412257   4.651530   
1  14839  1432.410201  10.663869   7.079026   8.065215   5.297097   5.297097   
2  14840    83.352608   3.931852   1.774215   1.774215   1.073446   1.073446   
3  14841   150.255712   5.912790   3.548812   3.548812   2.595128   2.595128   
4  14842  1817.276351  24.910940  15.540529  20.047314  12.535886  17.730988   

       Chi3v     Chi4n  EState_VSA1  ...  PEOE_VSA14  PEOE_VSA6  PEOE_VSA7  \
0   2.096558  1.116433    49.458581  ...   13.512441   0.000000   0.000000   
1   3.924155  2.569694     0.000000  ...    0.000000  34.947374  98.323987   
2   0.467830  0.170838     5.969305  ...    5.969305   0.000000   0.000000   
3   1.642813  0.694113     0.000000  ...   59.935299   0.000000   0.000000   
4  11.979618  4.431173    84.554972  ...   23.468091  25.609359   0.000000   

   PEOE_VSA8  SMR_VSA10   SMR_VSA5  SlogP_VSA3  VSA_EState9  fr_COO  fr_COO2  
0   0.000000  26.809272  24.539800    4.794537    47.304082       1        1  
1   9.606882   0.000000  53.378235    0.000000    43.166667       0        0  
2   6.420822  11.752550  13.344559    9.589074    24.666667       1        1  
3   0.000000  17.744066  32.290168    4.794537    26.778866       0        0  
4  37.099000  69.141353  38.704130   50.697492   102.583333       0        0  

[5 rows x 32 columns]

## Exploring testing data

In [11]:
df_test.shape

(9893, 32)

In [12]:
df_test.size

316576

In [13]:
df_test.describe()

id      BertzCT         Chi1        Chi1n        Chi1v  \
count   9893.00000  9893.000000  9893.000000  9893.000000  9893.000000   
mean   19784.00000   516.411916     9.106998     5.848047     6.733659   
std     2856.00744   544.327795     6.754583     4.641662     5.863886   
min    14838.00000     0.000000     0.000000     0.000000     0.000000   
25%    17311.00000   150.255712     4.698377     2.846050     2.934030   
50%    19784.00000   289.901774     6.447265     4.009996     4.337841   
75%    22257.00000   652.758463    10.966946     7.490880     8.528316   
max    24730.00000  3919.541449    53.876516    43.283925    53.990574   

             Chi2n        Chi2v        Chi3v        Chi4n  EState_VSA1  ...  \
count  9893.000000  9893.000000  9893.000000  9893.000000  9893.000000  ...   
mean      4.428979     5.247994     3.401083     1.750078    28.956335  ...   
std       3.770031     4.939702     3.431766     1.837159    31.470865  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       1.949719     2.049137     1.171060     0.508512     5.969305  ...   
50%       2.930013     3.168052     1.923982     1.058931    17.282269  ...   
75%       5.788793     6.516914     4.302610     2.509394    44.876559  ...   
max      36.368883    44.726398    26.736931    15.620667   363.705954  ...   

        PEOE_VSA14    PEOE_VSA6    PEOE_VSA7    PEOE_VSA8    SMR_VSA10  \
count  9893.000000  9893.000000  9893.000000  9893.000000  9893.000000   
mean     18.493154     8.917260    11.222822     6.789234    15.810550   
std      35.832279    19.358857    20.015732    10.778071    18.265549   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     5.969305   
50%       5.969305     0.000000     5.563451     0.000000    11.752550   
75%      17.907916    12.132734    13.344559     6.923737    17.744066   
max     482.434223   258.844527   271.424271    96.917997    79.920667   

          SMR_VSA5   SlogP_VSA3  VSA_EState9       fr_COO      fr_COO2  
count  9893.000000  9893.000000  9893.000000  9893.000000  9893.000000  
mean     30.919849    13.601593    49.426755     0.459719     0.461235  
std      33.532665    14.689893    29.542758     0.676657     0.677194  
min       0.000000     0.000000    -5.061146     0.000000     0.000000  
25%       6.420822     4.794537    30.000000     0.000000     0.000000  
50%      19.765380     9.589074    41.666667     0.000000     0.000000  
75%      42.727765    14.383612    56.083333     1.000000     1.000000  
max     492.729739   115.406157   384.450519     8.000000     8.000000  

[8 rows x 32 columns]

In [14]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9893 entries, 0 to 9892
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 9893 non-null   int64  
 1   BertzCT            9893 non-null   float64
 2   Chi1               9893 non-null   float64
 3   Chi1n              9893 non-null   float64
 4   Chi1v              9893 non-null   float64
 5   Chi2n              9893 non-null   float64
 6   Chi2v              9893 non-null   float64
 7   Chi3v              9893 non-null   float64
 8   Chi4n              9893 non-null   float64
 9   EState_VSA1        9893 non-null   float64
 10  EState_VSA2        9893 non-null   float64
 11  ExactMolWt         9893 non-null   float64
 12  FpDensityMorgan1   9893 non-null   float64
 13  FpDensityMorgan2   9893 non-null   float64
 14  FpDensityMorgan3   9893 non-null   float64
 15  HallKierAlpha      9893 non-null   float64
 16  HeavyAtomMolWt     9893 

In [15]:
#checking null values
df_test.isnull().sum()

id                   0
BertzCT              0
Chi1                 0
Chi1n                0
Chi1v                0
Chi2n                0
Chi2v                0
Chi3v                0
Chi4n                0
EState_VSA1          0
EState_VSA2          0
ExactMolWt           0
FpDensityMorgan1     0
FpDensityMorgan2     0
FpDensityMorgan3     0
HallKierAlpha        0
HeavyAtomMolWt       0
Kappa3               0
MaxAbsEStateIndex    0
MinEStateIndex       0
NumHeteroatoms       0
PEOE_VSA10           0
PEOE_VSA14           0
PEOE_VSA6            0
PEOE_VSA7            0
PEOE_VSA8            0
SMR_VSA10            0
SMR_VSA5             0
SlogP_VSA3           0
VSA_EState9          0
fr_COO               0
fr_COO2              0
dtype: int64

In [16]:
#checking duplicate values
df_test.duplicated().sum()

0

### Observation:

There are 32 columns and nearly 10000 rows. All columns are numerical in nature. There are no duplicates and neither are there any null values.

### Removing unnecessary columns

In [17]:
del df_test["id"]
df_test.head(2)

BertzCT       Chi1     Chi1n     Chi1v     Chi2n     Chi2v     Chi3v  \
0   344.632371   7.283603  4.473966  5.834958  3.412257  4.651530  2.096558   
1  1432.410201  10.663869  7.079026  8.065215  5.297097  5.297097  3.924155   

      Chi4n  EState_VSA1  EState_VSA2  ...  PEOE_VSA14  PEOE_VSA6  PEOE_VSA7  \
0  1.116433    49.458581     0.000000  ...   13.512441   0.000000   0.000000   
1  2.569694     0.000000    29.783175  ...    0.000000  34.947374  98.323987   

   PEOE_VSA8  SMR_VSA10   SMR_VSA5  SlogP_VSA3  VSA_EState9  fr_COO  fr_COO2  
0   0.000000  26.809272  24.539800    4.794537    47.304082       1        1  
1   9.606882   0.000000  53.378235    0.000000    43.166667       0        0  

[2 rows x 31 columns]

## Importing target variable

In [18]:
target = pd.read_csv(r"C:\Users\dell\Downloads\sample_submission (6).csv")
target.head()

id  EC1  EC2
0  14838  0.5  0.5
1  14839  0.5  0.5
2  14840  0.5  0.5
3  14841  0.5  0.5
4  14842  0.5  0.5

## Model Building using Logistic Regression

* ### Import model

In [19]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()

* ### Predicting variable EC1

In [20]:
# Defining variables
xtrain = df_train.iloc[:,:-6]
ytrain_EC1 = df_train.iloc[:,-6]
xtest = df_test
ytest_EC1 = target.iloc[:,1]

In [21]:
# Fitting data
log_model.fit(xtrain, ytrain_EC1)

LogisticRegression()

In [22]:
# Prediction
ypredtest_EC1 = log_model.predict(xtest)
ypredtest_EC1

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [23]:
# Finding probability
ypredprob_EC1 = log_model.predict_proba(xtest)
ypredprob_EC1

array([[0.4065044 , 0.5934956 ],
       [0.15238838, 0.84761162],
       [0.25668992, 0.74331008],
       ...,
       [0.4332219 , 0.5667781 ],
       [0.42925546, 0.57074454],
       [0.45462316, 0.54537684]])

* ### Predicting variable EC2

In [24]:
# Defining variables
xtrain = df_train.iloc[:,:-6]
ytrain_EC2 = df_train.iloc[:,-5]
xtest = df_test
ytest_EC2 = target.iloc[:,2]

In [25]:
# Fitting data
log_model.fit(xtrain, ytrain_EC2)

LogisticRegression()

In [26]:
# Prediction
ypredtest_EC2 = log_model.predict(xtest)
ypredtest_EC2

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [27]:
# Finding probability
ypredprob_EC2 = log_model.predict_proba(xtest)
ypredprob_EC2

array([[0.20355257, 0.79644743],
       [0.16381527, 0.83618473],
       [0.23105212, 0.76894788],
       ...,
       [0.17157479, 0.82842521],
       [0.14014904, 0.85985096],
       [0.15761637, 0.84238363]])

In [28]:
#Saving predictions in sample submission file
probabilities = pd.DataFrame(ypredprob_EC1[:,1])
file11 = probabilities.to_csv("Final Submission using Logistic Regression 3-7-23.csv", index = False)

file11 = pd.read_csv("Final Submission using Logistic Regression 3-7-23.csv")
file11 = pd.concat([target['id'],probabilities,pd.DataFrame(ypredprob_EC2[:,1])], axis = 1)
file11.columns = ["id", "EC1","EC2"]
file11.to_csv("Final Submission using Logistic Regression 3-7-23.csv", index = False)

## Reference

https://www.kaggle.com/competitions/playground-series-s3e18/data